=== BlackBeltTechnology/epsilon-runtime/epsilon-runtime-execution/src/main/resources/org/eclipse/epsilon/egl/config/ContentTypes.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT ContentTypes (ContentType*)>

<!ELEMENT ContentType (CommentStyle+)>
<!ATTLIST ContentType
          name CDATA #REQUIRED>

<!ELEMENT CommentStyle EMPTY>
<!ATTLIST CommentStyle
          startsWith CDATA ""
          endsWith CDATA ""
>

=== BlackBeltTechnology/epsilon-runtime/epsilon-runtime-execution/src/main/resources/org/eclipse/epsilon/egl/config/DefaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  #%L
  epsilon-runtime-execution
  %%
  Copyright (C) 2018 - 2023 BlackBelt Technology
  %%
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  #L%
  -->

<!DOCTYPE ContentTypes SYSTEM "http://www.epsilon.org/egl/ContentTypes.dtd">

<ContentTypes>
	<ContentType name="Java">
		<CommentStyle startsWith="//" />
		<CommentStyle startsWith="/*" endsWith="*/" />
	</ContentType>
	
	<ContentType name="HTML">
		<CommentStyle startsWith="&lt;!--" endsWith="--&gt;"/>
	</ContentType>

	<ContentType name="VisualBasic">
		<CommentStyle startsWith="&apos;" />
	</ContentType>
	
	<ContentType name="EGL">
		<CommentStyle startsWith="--" />
	</ContentType>
	
	<ContentType name="Perl">
		<CommentStyle startsWith="#" />
	</ContentType>
</ContentTypes>
